language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  secure: "ELC4rD8nn2l5T48WYbTfcbwGGBmNxl7LAu05hgx5AB9/KA+oD3oBKIJkZqD512gJ31Gtyla/hG9QOgU7LikfWdpGuJjVILy01ZqtgP5SSKsrTdlln1D5pK1ZyHJNrEPevb3W5PYn9ahHnjKGtpobXj4/E0sCXfRPH67jv9hffYs="

before_install:
  - go get -u github.com/haya14busa/goverage

script:
  - goverage -v -coverprofile=coverage.txt -covermode=count ./vm ./env . ./ast/astutil

after_success:
  - bash <(curl -s https://codecov.io/bash)
